### ISSUE TITLE
Missing paranthesis

### ISSUE THREAD

**Issue by aniket2610-cyber** [anubhavanonymous/MailBlast#1]
~/MailBlast $ python main.py
  File "/data/data/com.termux/files/home/MailBlast/main.py", line 17
    print bcolors.OKGREEN + '''
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(bcolors.OKGREEN + ''')?
~/MailBlast $

This ia the issue i am facing..

**Comment by anubhavanonymous** [comment]
It's based on python2 !
```python2 main.py```
If you do not have python2 on your system 
Install it...
Kali Linux - ```sudo apt-get install python2```
Termux - ```apt install python2```

**Comment by anubhavanonymous** [comment]
I will shift this project to python3 
Soon....!

**Comment by aniket2610-cyber** [comment]
Using python 2
